default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV['POSTGRESQL_CONTAINER'].present? %>
  host: db
  username: postgres
  password: password
  <% end %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RoomMasterApi_development

test:
  <<: *default
  database: RoomMasterApi_test

production:
  <<: *default
  database: RoomMasterApi_production
  username: RoomMasterApi
  password: <%= ENV["ROOMMASTERAPI_DATABASE_PASSWORD"] %>
